name: app
type: 'php:8.2'

dependencies:
  php:
      composer/composer: '^2'

runtime:
  extensions:
      - pdo_pgsql
      - sodium

variables:
  php:
      opcache.preload: config/preload.php

relationships:
  database: "database:postgresql"

mounts:
  'api/public/thumbnails':
    source: local
    source_path: thumbnails
  'api/public/videos':
    source: local
    source_path: videos
  'api/var/log':
    source: local
    source_path: log
  'api/var/cache':
    source: local
    source_path: cache
  'api/config/jwt':
    source: local
    source_path: jwt

# The size of the persistent disk of the application (in MB).
disk: 2048

hooks:
    build: |
      set -x -e
      cd api
      curl -fs https://get.symfony.com/cloud/configurator | bash
      COMPOSER_FLAGS="--no-dev" NODE_VERSION=18 symfony-build
    deploy: |
      set -x -e
      cd api
      symfony-deploy

web:
  locations: 
    '/': 
      root: "api/public"
      passthru: "/index.php"
      allow: true

