name: app
type: 'php:8.2'

dependencies:
  php:
    composer/composer: '^2'

runtime:
  extensions:
    - pdo_pgsql
    - sodium

variables:
  php:
    opcache.preload: config/preload.php

build:
  flavor: none

relationships:
  database: "db:postgresql"

mounts:
  'var': { source: local, source_path: var }

# The size of the persistent disk of the application (in MB).
disk: 2048

web:
  locations: 
    '/': 
      root: "public"
      passthru: "/index.php"
      allow: true

hooks:
    build: |
      set -x -e
      curl -fs https://get.symfony.com/cloud/configurator | bash
      symfony-build
      php bin/console lexik:jwt:generate-keypair
    deploy: |
      set -x -e
      symfony-deploy