name: app
type: 'nodejs:18'

disk: 2048
build:
  flavor: none

dependencies:
  nodejs:
    yarn: "*"

web:
  # doc: https://docs.platform.sh/create-apps/web/static.html
  locations:
    "/":
      root: "dist"
      index:
        - "index.html"
      scripts: false
      allow: true
      expires: 300s
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        \/(.+/?)+$:
          index:
          - "index.html"

    # "/home":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # "/login":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # "/signup":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # ^(/dashboard/)(.+)$:
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # "/verify-registration":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # "/forget-password":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
    # "/reset-password":
    #   root: "dist"
    #   index:
    #     - "index.html"
    #   scripts: false
    #   allow: true
    #   expires: 300s
        
  commands:
    start: sleep infinity

hooks:
  build: |
    set -x -e
    yarn install --frozen-lockfile
    yarn build
