vich_uploader:
    db_driver: orm
    metadata:
      type: attribute
    mappings:
      thumbnails: 
        uri_prefix: /thumbnails
        upload_destination: '%kernel.project_dir%/fixtures/thumbnails'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      
      medialinks:
        uri_prefix: /videos
        upload_destination: '%kernel.project_dir%/fixtures/videos'
        # Will rename uploaded files using a uniqueid as a prefix.
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer