name: app
type: 'nodejs:18'

disk: 2048
build:
  flavor: none

dependencies:
  nodejs:
    yarn: "*"

web:
  # doc: https://docs.platform.sh/create-apps/web/static.html
  locations:
    "/":
      root: "dist"
      index:
        - "index.html"
      scripts: false
      allow: true
      expires: 300s
      rules:
        \.(css|js|gif|jpe?g|png|ttf|eot|woff2?|otf|html|ico|svg?)$:
          allow: true
        \/(.+/?)+$:
          passthru: "/index.html"
  commands:
    start: sleep infinity

hooks:
  build: |
    set -x -e
    yarn install --frozen-lockfile
    yarn build
