controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
auth:
    path: /api/login
    methods: ['POST']

send_confirmation_email:
    path: /api/send-confirmation-email
    methods: ['POST']
    controller: App\Controller\ConfirmationEmailController