# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.api_default_uri: '%env(API_DEFAULT_URI)%'
    app.api_client_url: '%env(API_CLIENT_URL)%'
    app.api_transactional_email_address: '%env(TRANSACTIONAL_EMAIL_ADDRESS)%'
    app.api_stripe_publichable_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
    app.api_end_point_secret: '%env(END_POINT_SECRET)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'


    App\State\UserProcessor: ~
    
    # password hasher for the User entity
    App\State\UserPasswordHasher:
        bind:
            $processor: '@api_platform.doctrine.orm.state.persist_processor'
    
    App\State\ContentReviewProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
    
    App\State\BeReviewerApplicationValidationProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
    
    App\Serializer\ApiNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
        tags:
            - { name: 'serializer.normalizer', priority: 64 }
    
    App\Serializer\CourseContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\CourseContextBuilder.inner' ]
        autoconfigure: false

    App\Serializer\BeReviewerApplicationContextBuilder:
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\BeReviewerApplicationContextBuilder.inner' ]
        autoconfigure: false
    
    App\Serializer\UploadedFileNormalizer:
        arguments:
            $apiDefaultUri: '%app.api_default_uri%'
        tags: ['serializer.normalizer']
    
    App\Encoder\MultipartDecoder:
        tags: [ 'serializer.encoder' ]

    # hash user fixtures password
    App\DataFixtures\Processor\UserProcessor:
        arguments: ['@security.user_password_hasher']

    App\EventListener\LoginSuccessListener:
        arguments:
            - '@serializer'
            - '@lexik_jwt_authentication.encoder'
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccess }

    App\Service\VerifyEmailService:
        arguments:
            $apiClientUrl: '%app.api_client_url%'
    
    App\Service\MailService:
        arguments:
            $from: '%app.api_transactional_email_address%'

    App\Controller\StripeController:
        arguments:
            $stripe_publichable_key: '%app.api_stripe_publichable_key%'
            $end_point_secret: '%app.api_end_point_secret%'
            $front_url: '%app.api_client_url%'
    
    App\Processor\SendConfirmationEmailProcessor: ~
    
    App\State\ReviewersProvider: ~
    
    App\State\PublishedCoursesProvider: ~

    App\State\ValidationRequestProcessor:
        bind:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'

    # App\Controller\SendEmailController:
    #     arguments: ['@app.mail_service']
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
