name: deploy api on platform.sh

on:
  push:
    branches:
      - api

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    steps:
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          php-version: 8.1
          force-push: true
          environment-name: main