name: deploy front on platform.sh

on:
  push:
    branches:
      - front

jobs:
  deploy-front:
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/front' }}
    steps:
      - uses: axelerant/platformsh-deploy-action@v1
        with:
          project-id: ${{ secrets.PLATFORM_PROJECT_ID }}
          cli-token: ${{ secrets.PLATFORM_CLI_TOKEN }}
          force-push: true
          environment-name: main